import { Button, VerticalBox, GridBox, LineEdit, CheckBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: @tr("Bérkalkulátor");
    in property <string> results: "";
    callback divide-income(string, bool, bool);
    background: darkviolet;
    GridLayout {
        padding: 40px;
        spacing: 25px;
        Row {
            Text {
                text: @tr("Bérkalkulátor 2024");
                horizontal-alignment: center;
                color: white;
                font-size: 24px;
                font-weight: 1000;
            }
        }
        Row {
            income := LineEdit {
                input-type: number;
                font-size: 16px;            
                horizontal-alignment: center;
                placeholder-text: @tr("Bruttó havi bére (Ft)");
                height: 40px;
            }
        }
        Row {
            friss_hazas_box := CheckBox {
                text: @tr("Friss házasok kedvezménye");
            }         
        }
        Row {
            szja_mentes := CheckBox {
                text: @tr("25 év alattiak szja-mentessége");
            }         
        }
        Row {
            Button {
                text: @tr("Kiszámol");
                primary: true;
                height: 40px;
                clicked => {divide-income(income.text, friss-hazas-box.checked, szja-mentes.checked)}
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 280px;
                    width: 500px;
                    background: #f2f2f2;
                    Text {
                        color: darkblue;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
