import { Button, VerticalBox, GridBox, LineEdit, CheckBox, Switch } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: @tr("Salary calculator");
    in property <string> results: "";
    callback divide-income(string, bool, bool, bool);
    background: darkolivegreen;
    width: 450px;
    height: 600px;
    GridLayout {
        padding: 10px;
        spacing: 8px;
        Row {
            GridLayout {
                Row {
                    Image {
                        image-fit: ImageFit.contain;
                        height: 80px;
                        width: 60px;
                        source: @image-url("cash-1296584_640.png");
                    }
                    Text {
                        text: @tr("Salary calculator 2024");
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        color: white;
                        font-size: 20px;
                        font-weight: 600;
                    }
                }
            }
        }
        Row {
            income := LineEdit {
                input-type: number;
                font-size: 16px;            
                horizontal-alignment: center;
                placeholder-text: @tr("Gross monthly salary (HUF)");
                height: 40px;
            }
        }
        Row {
            friss_hazas_box := CheckBox {
                text: @tr("Discount for newlyweds");
            }         
        }
        Row {
            szja_mentes := CheckBox {
                text: @tr("Exemption for persons under the age of 25");
            }         
        }
        Row {
            csv_export := Switch {
                text: @tr("Export result to CSV file");
            }
        }
        Row {
            Button {
                text: @tr("Calculate");
                primary: true;
                height: 40px;
                clicked => {divide-income(income.text, friss-hazas-box.checked, szja-mentes.checked, csv_export.checked)}
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 280px;
                    width: 400px;
                    background: #f2f2f2;
                    Text {
                        color: darkblue;
                        font-size: 12px;
                        font-weight: 400;
                        text: root.results;
                    }
                }
            }
        }
    }
}
