import { Button, VerticalBox, GridBox, LineEdit, CheckBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: @tr("Salary calculator");
    in property <string> results: "";
    callback divide-income(string, bool, bool);
    background: darkviolet;
    GridLayout {
        padding: 40px;
        spacing: 25px;
        Row {
            Text {
                text: @tr("Salary calculator 2024");
                horizontal-alignment: center;
                color: white;
                font-size: 24px;
                font-weight: 1000;
            }
        }
        Row {
            income := LineEdit {
                input-type: number;
                font-size: 16px;            
                horizontal-alignment: center;
                placeholder-text: @tr("Gross monthly salary (HUF)");
                height: 40px;
            }
        }
        Row {
            friss_hazas_box := CheckBox {
                text: @tr("Discount for newlyweds");
            }         
        }
        Row {
            szja_mentes := CheckBox {
                text: @tr("Exemption for persons under the age of 25");
            }         
        }
        Row {
            Button {
                text: @tr("Calculate");
                primary: true;
                height: 40px;
                clicked => {divide-income(income.text, friss-hazas-box.checked, szja-mentes.checked)}
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 280px;
                    width: 500px;
                    background: #f2f2f2;
                    Text {
                        color: darkblue;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
